spring:
  application:
    name: orders-grpc
  jmx:
    enabled: false
  grpc:
    server:
      port: 9091
    client:
      channels:
        product-service:
          address: "static://localhost:9090"
#          negotiation-type: plaintext #Enable this if TLS configs are disabled
          ssl:
            bundle: product-ssl
          negotiation-type: TLS
  ssl:
    bundle:
      jks:
        product-ssl:
          truststore:
            location: classpath:certs/java-grpc.jks
            password: java-grpc
            type: JKS